# Generated by Django 4.0.2 on 2022-03-05 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='deleted at')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='deleted at')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='discount')),
                ('terms', models.TextField(blank=True, max_length=255, null=True, verbose_name='term and conditions')),
                ('instructions', models.TextField(blank=True, max_length=255, null=True, verbose_name='instructions')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='product image')),
                ('product_type', models.CharField(choices=[('F', 'Fisico'), ('D', 'Digital')], default='D', max_length=1)),
                ('iva', models.FloatField(verbose_name='IVA')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category product')),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='deleted at')),
                ('inventory', models.PositiveIntegerField(verbose_name='inventario')),
                ('available', models.PositiveIntegerField(verbose_name='disponible')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDigital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='deleted at')),
                ('redeem', models.BooleanField(blank=True, default=False, null=True, verbose_name='redeemed')),
                ('redeem_date', models.DateField(blank=True, null=True, verbose_name='redeemed date')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('link_redemption', models.CharField(blank=True, max_length=100, null=True, verbose_name='link redemption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdigital', to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'ProductDigital',
                'verbose_name_plural': 'ProductsDigital',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
