# Generated by Django 4.0.2 on 2022-03-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='iva',
            field=models.FloatField(default=0, verbose_name='IVA'),
        ),
    ]
