# Generated by Django 4.0.2 on 2022-03-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(max_length=255, verbose_name='product image'),
        ),
    ]
