version: '3.9' 
services:
  redis:
    image: "redis:alpine"
    networks: 
      - web_network
  db:
    container_name: db
    image: postgres:13.3-alpine
    volumes:
      - ecommercedb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Ecommerce_app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db_network
  web:
    container_name: web
    restart: always
    env_file: .env
    build: .
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    networks:
      - db_network
      - web_network
    depends_on:
      - db
      - redis
    
  celery:
    build: .
    command: celery -A Ecommerce worker --loglevel=info
    volumes:
      - .:/code
    networks:
      - db_network
      - web_network
    depends_on:
      - web 
      - db
      - redis
    
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports: 
      - "85:85"
    volumes: 
      - ./nginx:/etc/nginx/conf.d 
    networks: 
      - web_network
    depends_on: 
      - web
      - db
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  ecommercedb:
    external: true
